### ISSUE TITLE
Incorrect syntax

### ISSUE THREAD

**Issue by Aotoge** [wendcoin/wend.github.io#2]
Looks like your index file does not follow proper html syntax.
You can try resources like [codeacademy](https://www.codecademy.com/learn/learn-html) to learn the basics of html for making websites!
Till then here is some replacement code you can use in the file!

![wend](https://user-images.githubusercontent.com/22166269/34095553-d47381b2-e3f7-11e7-9f14-befccdf376f6.jpg)

**Comment by wendcoin** [comment]
Thank you Aotoge.  You are awesome!
